# Generated by Django 4.2.16 on 2024-10-16 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profileapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="meal_categories",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="profile",
            name="saltiness",
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name="profile",
            name="sourness",
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name="profile",
            name="spiciness",
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name="profile",
            name="sweetness",
            field=models.IntegerField(default=3),
        ),
    ]
