# Generated by Django 4.2.16 on 2024-10-16 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profileapp", "0002_profile_meal_categories_profile_saltiness_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="meal_categories",
            new_name="categories",
        ),
        migrations.AddField(
            model_name="profile",
            name="cleanliness",
            field=models.IntegerField(default=3),
        ),
    ]
