# Generated by Django 4.2.16 on 2024-10-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0004_profile_asian_profile_bar_profile_bistro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='categories',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
