# Generated by Django 4.2.16 on 2024-10-16 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("description", models.TextField(null=True)),
                ("link", models.CharField(max_length=255)),
                ("sweetness", models.FloatField(default=3)),
                ("spiciness", models.FloatField(default=3)),
                ("saltiness", models.FloatField(default=3)),
                ("sourness", models.FloatField(default=3)),
                ("cleanliness", models.FloatField(default=3)),
                ("category", models.CharField(max_length=255)),
            ],
        ),
    ]
