# Generated by Django 4.2.16 on 2024-10-19 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biz_id', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('sweetness', models.FloatField(default=3)),
                ('spiciness', models.FloatField(default=3)),
                ('saltiness', models.FloatField(default=3)),
                ('sourness', models.FloatField(default=3)),
                ('cleanliness', models.FloatField(default=3)),
                ('category', models.CharField(max_length=255)),
                ('score', models.FloatField(default=3)),
                ('recommendations', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField(null=True)),
                ('sweetness', models.IntegerField(null=True)),
                ('spiciness', models.IntegerField(null=True)),
                ('saltiness', models.IntegerField(null=True)),
                ('sourness', models.IntegerField(null=True)),
                ('cleanliness', models.IntegerField(null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venueapp.venue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
