# Generated by Django 4.2.16 on 2024-10-16 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("venueapp", "0002_uservisit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="venue",
            name="description",
        ),
    ]
