# Generated by Django 4.2.16 on 2024-10-17 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venueapp', '0003_remove_venue_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='biz_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
