# Generated by Django 4.2.16 on 2024-10-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venueapp', '0004_venue_biz_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='id',
        ),
        migrations.AddField(
            model_name='venue',
            name='recommendations',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='venue',
            name='score',
            field=models.FloatField(default=3),
        ),
        migrations.AlterField(
            model_name='venue',
            name='biz_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
